sudo: false
language: php
before_script:
  - composer install --dev --no-interaction
  - wget https://scrutinizer-ci.com/ocular.phar
php:
  - 5.4
  - 5.5
  - 5.6
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - ./vendor/bin/phpcs --standard=PSR1 lib/
  - ./vendor/bin/phpcs --standard=PSR2 lib/
